name: Gitleaks Scan

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source ${{ inputs.path }} --exit-code 1
